import * as fs from 'fs';
import * as path from 'path';
import { WorkflowReport } from '../models/WorkflowModels';
import { BehavioralGraph } from '../models/GraphModels';

/**
 * Exports a workflow-first onboarding map for new engineers.
 *
 * Output is a directory of markdown files, one per workflow, plus an index.
 * Each file lists members, internal edge topology, runtime risks, and
 * a "Where to start reading" hint pointing at the highest-fan-in node.
 */
export interface OnboardingExportResult {
    outputDir: string;
    indexPath: string;
    workflowPaths: string[];
}

export class OnboardingExporter {
    public export(projectRoot: string, workflowReport: WorkflowReport, graph: BehavioralGraph): OnboardingExportResult {
        const outDir = path.join(projectRoot, 'veris-reports', 'onboarding');
        if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

        const fanIn = computeFanIn(graph);
        const workflowPaths: string[] = [];

        for (const wf of workflowReport.workflows) {
            const agg = workflowReport.aggregates.find(a => a.workflowId === wf.id);
            const members = wf.memberNodeIds;
            // Highest fan-in node within the workflow = the "hub"
            const memberSet = new Set(members);
            const hub = members
                .map(id => ({ id, score: fanIn.get(id) || 0 }))
                .sort((a, b) => b.score - a.score)[0];

            const internalEdges = graph.getEdges().filter(e =>
                memberSet.has(e.sourceId) && memberSet.has(e.targetId)
            ).slice(0, 50);

            let md = `# Onboarding — ${wf.name}\n\n`;
            md += `> ${agg?.narrative || 'Workflow boundary identified by Veris classifier.'}\n\n`;
            md += `**Kind:** ${wf.kind} • **Members:** ${members.length} • **Classifier confidence:** ${wf.confidence}/100\n\n`;
            md += `## Where to start reading\n\n`;
            if (hub) {
                md += `Highest fan-in node — start here:\n\n\`${hub.id}\` (fan-in: ${hub.score})\n\n`;
            }
            md += `## Runtime risks to keep in mind\n\n`;
            for (const risk of agg?.runtimeRisks || []) md += `- ${risk}\n`;
            if ((agg?.runtimeRisks || []).length === 0) md += `- _No workflow-specific runtime risks recorded._\n`;
            md += `\n## Inference signals (why these nodes are grouped)\n\n`;
            for (const s of wf.signals.slice(0, 10)) md += `- \`${s.source}\`: \`${s.value}\` (weight ${s.weight})\n`;
            md += `\n## Members\n\n`;
            for (const id of members) md += `- \`${id}\`\n`;
            md += `\n## Internal call topology (up to 50 edges)\n\n`;
            for (const e of internalEdges) md += `- \`${shortId(e.sourceId)}\` -[${e.type}]-> \`${shortId(e.targetId)}\`\n`;

            const file = path.join(outDir, `${wf.id}.md`);
            fs.writeFileSync(file, md, 'utf8');
            workflowPaths.push(file);
        }

        // Index
        let idx = `# Onboarding Map\n\nGenerated by Veris. Workflow-first view of this codebase.\n\n`;
        idx += `## Workflows\n\n`;
        for (const wf of workflowReport.workflows) {
            const agg = workflowReport.aggregates.find(a => a.workflowId === wf.id);
            idx += `- **[${wf.name}](./${wf.id}.md)** — ${wf.memberNodeIds.length} nodes`;
            if (agg && agg.maxRisk > 0) idx += ` (max risk ${agg.maxRisk.toFixed(0)})`;
            idx += `\n`;
        }
        idx += `\n## How to read this\n\nEach workflow is a behavioral cluster, not a directory. ` +
               `Start at the "Where to start reading" hub of the workflow you own. ` +
               `Cross-workflow contracts are visible in the parent dashboard.\n`;

        const indexPath = path.join(outDir, 'README.md');
        fs.writeFileSync(indexPath, idx, 'utf8');

        return { outputDir: outDir, indexPath, workflowPaths };
    }
}

function shortId(id: string): string {
    return id.split('/').slice(-2).join('/');
}

function computeFanIn(graph: BehavioralGraph): Map<string, number> {
    const map = new Map<string, number>();
    for (const e of graph.getEdges()) {
        map.set(e.targetId, (map.get(e.targetId) || 0) + 1);
    }
    return map;
}
